#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Text-Trim
Version  : 1.04
Release  : 16
URL      : https://cpan.metacpan.org/authors/id/R/RJ/RJT/Text-Trim-1.04.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RJ/RJT/Text-Trim-1.04.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtext-trim-perl/libtext-trim-perl_1.02-2.debian.tar.xz
Summary  : 'remove leading and/or trailing whitespace from strings'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Text-Trim-license = %{version}-%{release}
Requires: perl-Text-Trim-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
NAME
Text::Trim - remove leading and/or trailing whitespace from strings
VERSION
version 1.04

%package dev
Summary: dev components for the perl-Text-Trim package.
Group: Development
Provides: perl-Text-Trim-devel = %{version}-%{release}
Requires: perl-Text-Trim = %{version}-%{release}

%description dev
dev components for the perl-Text-Trim package.


%package license
Summary: license components for the perl-Text-Trim package.
Group: Default

%description license
license components for the perl-Text-Trim package.


%package perl
Summary: perl components for the perl-Text-Trim package.
Group: Default
Requires: perl-Text-Trim = %{version}-%{release}

%description perl
perl components for the perl-Text-Trim package.


%prep
%setup -q -n Text-Trim-1.04
cd %{_builddir}
tar xf %{_sourcedir}/libtext-trim-perl_1.02-2.debian.tar.xz
cd %{_builddir}/Text-Trim-1.04
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Text-Trim-1.04/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Text-Trim
cp %{_builddir}/Text-Trim-1.04/LICENSE %{buildroot}/usr/share/package-licenses/perl-Text-Trim/2953a676055661791ce3e4e64cdeea1742804467
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Text-Trim/cf906538fb52df1de1642df1a81365e7969b101e
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Text::Trim.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Text-Trim/2953a676055661791ce3e4e64cdeea1742804467
/usr/share/package-licenses/perl-Text-Trim/cf906538fb52df1de1642df1a81365e7969b101e

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.32.1/Text/Trim.pm
