#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Text-Trim
Version  : 1.02
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/MA/MATTLAW/Text-Trim-1.02.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MA/MATTLAW/Text-Trim-1.02.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtext-trim-perl/libtext-trim-perl_1.02-2.debian.tar.xz
Summary  : remove leading and/or trailing whitespace from strings
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Text-Trim-man
BuildRequires : perl-Module-Build

%description
NAME
Text::Trim - remove leading and/or trailing whitespace from strings
VERSION
version 1.02

%package man
Summary: man components for the perl-Text-Trim package.
Group: Default

%description man
man components for the perl-Text-Trim package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Text-Trim-1.02
mkdir -p %{_topdir}/BUILD/Text-Trim-1.02/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Text-Trim-1.02/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Text/Trim.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Text::Trim.3
